import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import { Toaster } from '@/common/components/ui';

import '@/common/styles/globals.css';

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  preload: false,
  display: 'swap',
  fallback: ['Hiragino Sans', 'Hiragino Kaku Gothic ProN', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Layout: React.FC<{ children: React.ReactNode }> = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="ja"
      className={notoSansJP.className}
    >
      <body>
        <div className="p-4">
          <h1 className="mb-4 text-3xl font-bold underline">Test3</h1>
          <div>{children}</div>
          <Toaster />
        </div>
      </body>
    </html>
  );
};

export default Layout;
